service: Plataforma-APP

provider:
  name: aws
  runtime: nodejs18.x  # Usar Node.js 18.x (soportado por AWS Lambda)
  region: us-east-1
  stage: dev
  memorySize: 128  # Tamaño de memoria en MB (ajustable según necesidades)
  timeout: 10  # Tiempo máximo de ejecución en segundos
  environment:
    MAX_INTENTOS: 3
    TIEMPO_BLOQUEO: 60000
    USUARIO_ADMIN: usuarioValido
    PASSWORD_ADMIN: passwordValido

functions:
  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors:
            origin: '*'  # Permitir cualquier origen (ajustar en producción)
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
